### ISSUE TITLE
update_index --workers=2 crashes: 'ConnectionHandler' object has no attribute 'thread_local'

### ISSUE THREAD

**Issue by raphaelmerx** [django-haystack/django-haystack#1449]
* [x] Tested with the latest Haystack release
* [x] Tested with the current Haystack master branch

## Expected behaviour

`./manage.py update_index --workers 2` updates the index without crashing, like it does when using only one worker.

## Actual behaviour
`./manage.py update_index --workers 2` raises the following error:
```
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/var/www/mohinga/env/lib/python3.5/site-packages/haystack/management/commands/update_index.py", line 45, in update_worker
    if isinstance(connections.thread_local.connections, dict):
AttributeError: 'ConnectionHandler' object has no attribute 'thread_local'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/www/mohinga/env/lib/python3.5/site-packages/haystack/management/commands/update_index.py", line 214, in handle
    self.update_backend(label, using)
  File "/var/www/mohinga/env/lib/python3.5/site-packages/haystack/management/commands/update_index.py", line 265, in update_backend
    successful_tasks = pool.map(update_worker, ghetto_queue)
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
AttributeError: 'ConnectionHandler' object has no attribute 'thread_local'
```

## Steps to reproduce the behaviour
Run the above command using django-haystack==2.5.0. This bug does not appear on versions <2.5.0. It has been introduced in 4e1e2e1c.
Similar (same?) issue: https://github.com/django-haystack/django-haystack/issues/1422

## Configuration

* Operating system: Ubuntu 16.04. Also on OSX 10.11
* Elasticsearch v2.4.1. Also with Whoosh 2.5.5
* Python version: 3.5.2
* Django version: 1.9.10
* Haystack version: 2.5.0

**Comment by richardbarran** [comment]
Found the same issue.

- Ubuntu 14.04
- Elasticsearch 1.6.0
- Python 3.4.3
- Django 1.10.2
- Haystack 2.5.0

**Comment by acdha** [comment]
Looks like a simple mistake on my part – try https://github.com/acdha/django-haystack/commit/730ad4b9a19271c24e4cafc541a338f63fb35fda to confirm that it fixes the problem for you as well as it does for me.

**Comment by acdha** [comment]
This should be fixed in v2.5.1

**Comment by raphaelmerx** [comment]
Confirmed this fixes the problem. Thank you for the very quick fix @acdha
