### ISSUE TITLE
Whoosh 2.5 support

### ISSUE THREAD

**Issue by slav0nic** [django-haystack/django-haystack#819]
haystack 2.0 does't work with whoosh 2.5

```
ImportError: cannot import name SpellChecker
```

whoosh.spelling.SpellChecker class deprecated and was removed from Whoosh https://bitbucket.org/mchaput/whoosh/diff/src/whoosh/spelling.py?diff2=acbd1312c3f2&at=default
