### ISSUE TITLE
from django.utils import six Import error: cannot import name six 

### ISSUE THREAD

**Issue by KrikorHerlopian1** [django-haystack/django-haystack#1704]
I am working with Haystack 2.8.1 and django 3.0.1 and python 3.6 , getting the below error. Solutions looking for, did not solve it for me.the crash is happening in a file i cannot edit .

from django.utils import six Import error: cannot import name six 

django-admin-tools==0.8.1
django-admin-tools-stats==0.9.0
django-cache-utils==0.7.2
django-crispy-forms==1.8.1
django-haystack==2.8.1
django-jsonfield==1.4.0
django-nvd3==0.9.7
django-qsstats-magic==1.1.0
Jinja2==2.8
lxml==3.4.4
MarkupSafe==0.23
psycopg2==2.8.4
python-dateutil==2.4.2
python-memcached==1.57
python-nvd3==0.13.7
python-slugify==0.0.9
Unidecode==0.4.18
wheel==0.24.0
django-report-builder==6.3.2
djangorestframework==3.11.0
markdown==2.6.6
pinax-eventlog==1.1.1
data-importer==2.3.2
django-registration==3.0.1
django-excel==0.0.10
pyexcel==0.5.7
pyexcel-io==0.5.6
pyexcel-webio==0.0.7
pyexcel-xls==0.5.5
pyexcel-xlsx==0.5.5
texttable==0.8.4
xlwt==1.1.1
openpyxl==2.3.5
django-bower==5.2.0
django-notifications-hq==1.5.0
django-simple-captcha==0.5.12
pysolr==3.6.0
Django==3.0.1
django-mail-queue==3.2.2post1

**Comment by mke21** [comment]
'six' has been removed from django 3. I guess Haystack is not ready for that? See https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis

**Comment by acdha** [comment]
See #1702

**Comment by KrikorHerlopian1** [comment]
I hope haystack gets update for that, so i can move to django 3.0.1

**Comment by acdha** [comment]
@KrikorHerlopian1 Haystack is an entirely volunteer-supported project. If you have time to contribute to the open pull request (development, testing, or documentation) it will help that happen sooner.

**Comment by RomanAVolodin** [comment]
I guess there is no solution at all ... That's bad :(
