### ISSUE TITLE
SearchModelAdmin don't work with Django 1.4

### ISSUE THREAD

**Issue by efoken** [django-haystack/django-haystack#585]
`SearchModelAdmin` doesn't work correctly with Django 1.4. There is a missing argument 'list_max_show_all' for `SearchChangeList` in line 92. Also the `AdminSite` object has no attribute 'root_path' (line 119).
